### DISCUSSION TITLE
Direct URL Instead of Host and Port Field

### DISCUSSION THREAD

**Discussion by sadiesilverhand** [Dark-Alex-17/managarr#12] [Ideas]
Hey, would it be possible to modify the config file to accept a full URL instead of separate host and port fields? I have my *arr instances set up with domain forwarding through Caddy. It would be really helpful if I could just use the URL directly to access my instances without needing to be on my home network and use a local IP.

**Comment by Dark-Alex-17** [comment]
If you don't mind my asking, does it not work if you do something like this? Say I have Radarr hosted at `https://radarr.something.com`, would it work if your config looked like this:

```yaml
radarr:
    host: radarr.something.com
    port: 443
    use_ssl: true
    ssl_cert_path: /etc/radarr/radarr.crt
```

**Comment by Dark-Alex-17** [comment]
Either way, upon thinking about it more, you're right that this would be a good feature to have. 

I've published a new release, v0.2.1, that allows you to define your config either like this:

```yaml
radarr:
  host: 192.168.0.78
  port: 7878
  api_key: someApiKey
```

Or like this for your use case:

```yaml
radarr:
  uri: https://your.website.com/radarr
  api_key: someApiKey
  ssl_cert_path: /path/to/your/website.crt
```

Thanks for the suggestion, that's definitely a good idea.
