### DISCUSSION TITLE
Because I'm a weirdo who also wanted a web interface......

### DISCUSSION THREAD

**Discussion by stayupthetree** [Dark-Alex-17/managarr#22] [General]
Yes yes yes yes I know that somewhat defeats the purpose of the TUI/CLI, but sometimes its just easier to load a webpage and of course I wanted to a subdomain for it

## `docker-compose.yml`

```yaml
services:
  managarr:
    image: darkalex17/managarr:latest
    stdin_open: true
    tty: true
    container_name: managarr
    network_mode: bridge
    volumes:
      - ./config.yml:/root/.config/managarr/config.yml
      - /tmp:/tmp
    entrypoint: >
      sh -c "apt-get update &&
             apt-get install -y wget build-essential cmake libjson-c-dev zlib1g-dev libssl-dev &&
             wget -O /tmp/ttyd.x86_64 https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64 &&
             chmod +x /tmp/ttyd.x86_64 &&
             /tmp/ttyd.x86_64 -p 8080 managarr"
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.managarr.rule=Host(`managarr.example.com`)"
      - "traefik.http.routers.managarr.entrypoints=https"
      - "traefik.http.services.managarr.loadbalancer.server.port=8080"
      - "traefik.http.routers.managarr.tls.certresolver=myresolver"
```

## How to Start

1. Save the above `docker-compose.yml` file to a directory.
2. Create a `config.yml` file in the same directory for your `managarr` configuration.
3. Start the service with:
   ```bash
   docker-compose up -d
   ```

## Access

- **Without Traefik**: Open `http://<your-server-ip>:8080` in your browser.
- **With Traefik**: Open `https://managarr.example.com` (ensure your Traefik and DNS are configured).
