### DISCUSSION TITLE
https connections

### DISCUSSION THREAD

**Discussion by Count042** [Dark-Alex-17/managarr#6] [Ideas]
Is it possible to add the ability to connect to the *arr's through an https connection.

**Comment by Dark-Alex-17** [comment]
Funnily enough, I was literally finishing up this feature today. I just released v0.1.5 with HTTPS support.

So now, to enable HTTPS support, you need to update your config:

```yaml
---
radarr:
  host: localhost
  port: 9898
  api_token: someApiToken
  use_ssl: true
  ssl_cert_path: /path/to/radarr.crt
```

I also just want to take a moment to mention that all of the frequent releases right now are addressing bugs or good features to have for just Radarr support. So while I am currently releasing a new version each day to address these issues, it won't be forever. I'm expecting it to die down within a week, at which point I'm going to start working on Sonarr CLI support. 😃
