### ISSUE TITLE
Support environment variables in config.yml

### ISSUE THREAD

**Issue by BladeWDR** [Dark-Alex-17/managarr#23]
It doesn't seem like the YAML parser you're using supports environment variable expansion.

How difficult would it be to implement this?

Granted, my arrs are not publicly exposed, but I do store my dotfiles on GitHub, and I'd prefer not to have my API keys for them stored there for anyone to see.

Being able to load them from a .env file or system wide environment variables would be a nice enhancement.

Something like this:

```
radarr:
  uri: https://radarr.domain.xyz
  use_ssl: true
  api_token: ${RADARR_API_KEY}
sonarr:
  uri: https://sonarr.domain.xyz
  use_ssl: true
  api_token: ${SONARR_API_KEY}
```

I just started playing with this today, nice little project! :)
