### ISSUE TITLE
running from docker?

### ISSUE THREAD

**Issue by lgwapnitsky** [Dark-Alex-17/managarr#25]
I may be a bit daft, or I may be lacking coffee, but how do I run this from docker? I have the compose file up and running, but can't seem to locate the executable.

Thx

**Comment by Dark-Alex-17** [comment]
If I may, what does your docker compose look like?

**Comment by lgwapnitsky** [comment]
```
name: managarr
services:
    managarr:
        stdin_open: true
        tty: true
        volumes:
            - /opt/managarr/config.yml:/root/.config/managarr/config.yml
        image: darkalex17/managarr:latest
```
