### ISSUE TITLE
Error connecting sonarr instance

### ISSUE THREAD

**Issue by Amcro** [Dark-Alex-17/managarr#26]
### Summary

When I open Managarr TUI I get UI with Radarr and Sonarr tabs. After I switch to Sonarr tab i get this error:

![image](https://github.com/user-attachments/assets/e7e5e620-6990-42c5-ae6b-e25a03ab127c)

In config I have exact same setup for Sonarr and Radarr
```
radarr:
  host: radarr
  port: 7878
  api_token: My-API-Token
sonarr:
  uri: sonarr
  port: 8989
  api_token: My-API-Token
```
Everything works properly for Radarr, but Sonarr keeps showing this error. I've double checked API key just to be sure, tried to change from "sonarr" URI to IP address but I had exact same problem.
There is no report created so I don't have anything to upload as a log, I can only post this image.

### Platform

Linux/Unraid 

### Terminal Emulator

No emulator

### Managarr Version

Managarr 0.4.0
